// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dddgesmggivilqzjuisj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkZGdlc21nZ2l2aWxxemp1aXNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0Mzk5NzMsImV4cCI6MjA1ODAxNTk3M30.pM5LZJsVMUHKti_AAd0iAAMHvkTlvCHB_0GFhwxKDhw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);